#!/bin/bash
ulimit -SHn 51200
/usr/local/php/bin/spawn-fcgi -a 127.0.0.1 -p 10080 -C 256 -u www -f /usr/local/php/bin/php-cgi
if [ "$?" == "0" ];then
        echo "fastcgi启动成功"
else
        echo "fastcgi启动失败"
fi
