#!/bin/bash
tmp="'"
uptime=$(which uptime)
system_load=$($uptime | awk -F':' '{print $NF}' | sed 's/,//g')
one_load=$(echo $system_load| awk '{print $1}')
five_load=$(echo $system_load| awk '{print $2}')
fifteen_load=$(echo $system_load| awk '{print $1}')

case $1 in
1min)echo $one_load;;
5min)echo $five_load;;
15min)echo $fifteen_load;;
*)echo '##check_load##=>##{"1min":"'$one_load'","5min":"'$five_load'","15min":"'$fifteen_load'"}##||' | sed "s/##/$tmp/g";;
esac
